### ISSUE TITLE
Analysis failed with 311 in the notes

### ISSUE THREAD

**Issue by peilin** [synthego-open/ice#20]
Hi there,

we use ICE with docker install.  It is very easy and fast to use, thanks!

I am curious what exactly the error was if a sample failed analysis.  The log shows:

`-- analyzing 40 filename.ab1 GGTGAGTGAGTGTGTGCGTG`
`analyzing 462 number of edit proposals`
`R_SQUARED 0.998049444356253`
`discord (aln window): 0.07 after cutsite: 0.13`
`Exception Caught!`
`None`

I tried on your website, same "311" failed error.  Just curious what that means.

Thanks again, 

Pei

**Comment by peilin** [comment]
Hmm, I guess it's tricky to debug this one without the test data.  I downloaded the src and ran it locally.  This time I got the stack trace: 

> Exception Caught!
> Traceback (most recent call last):
>   File "~/ice/ice_env/lib/python3.6/site-packages/ice/analysis.py", line 79, in single_sanger_analysis
>     sa.analyze_sample()
>   File "~/ice/ice_env/lib/python3.6/site-packages/ice/classes/sanger_analysis.py", line 742, in analyze_sample
>     generate_trace_files(self, to_file=trace_file)
>   File "~/ice/ice_env/lib/python3.6/site-packages/ice/outputs/create_trace_files.py", line 117, in generate_trace_files
>     edited_end_bp = sanger_analysis.alignment.ctrl2sample_coords(downstream_in_bp, closest=True)
>   File "~/ice/ice_env/lib/python3.6/site-packages/ice/classes/pair_alignment.py", line 106, in ctrl2sample_coords
>     if self.control_to_sample[coord] is None and closest is True:
> KeyError: 311

Looks like coord is 311 and not in the dict, I am really new to the sequencing data, any suggestions what may have caused this?  Thanks!

**Comment by peilin** [comment]
I think I know what's going on.  Looks like a data quality issue.  The experiment ab1 file has 307 reads vs control has 460.  It would be good to catch this error upfront and give out a meaningful message like data quality is low.
