### ISSUE TITLE
pytest fail on v1.1.0

### ISSUE THREAD

**Issue by tdfy** [synthego-open/ice#26]
Hello, 

It is essential that I run a prior version to validate prior results. Please advise on the pytest failure, also observed in treatment data. Thanks. 

```
-------------------------------------------------- analyzing 8 donor_no_alignment AAGTGCAGCTCGTCCGGCGT
Base dir: /tmp/tmpxqi1g4d4/batch_analysis
Single Sanger analysis failed ord() expected string of length 1, but int found
Traceback (most recent call last):
  File "/home/tdfyoder/GIT/ice_v1.X/ice/ice/analysis.py", line 186, in multiple_sanger_analysis
    result = single_sanger_analysis(*job_args, **job_kwargs)
  File "/home/tdfyoder/GIT/ice_v1.X/ice/ice/analysis.py", line 77, in single_sanger_analysis
    donor=donor)
  File "/home/tdfyoder/GIT/ice_v1.X/ice/ice/classes/sanger_analysis.py", line 126, in initialize_with
    control_sample.initialize_from_path(control_path)
  File "/home/tdfyoder/GIT/ice_v1.X/ice/ice/classes/sanger_object.py", line 80, in initialize_from_path
    phred_scores.append(ord(c))
TypeError: ord() expected string of length 1, but int found
None of the samples were able to be analyzed
False
===================================== 14 failed, 31 passed in 1.82 seconds ======================================
```

**Comment by tdfy** [comment]
for fix refer to commit [04143d3](https://github.com/synthego-open/ice/commit/04143d3a5f5788498d179ad7a0eef84f22201e17#diff-cb2f8bcd61620aaa07ddaab0cdaea000)
