### ISSUE TITLE
AttributeError: 'MultipleSeqAlignment' object has no attribute 'format'

### ISSUE THREAD

**Issue by kiavash17** [synthego-open/ice#35]
Hi Thanks for sharing this tool. 
After installation when running the example I get the following error:

```
$ synthego_ice --control ./ice/tests/test_data/good_example_control.ab1 --edited ./ice/tests/test_data/good_example_edited.ab1 --target AACCAGTTGCAGGCGCCCCA --out results/testing --verbose

Synthego ICE (https://synthego.com)
Version: 1.1.1-alpha1
Base dir: /rhampseq/kkiaee/ice/ice/results
Exception Caught!
Traceback (most recent call last):
  File "/home/ccadmin/anaconda3/envs/ice_env/lib/python3.8/site-packages/ice/analysis.py", line 82, in single_sanger_analysis
    sa.analyze_sample()
  File "/home/ccadmin/anaconda3/envs/ice_env/lib/python3.8/site-packages/ice/classes/sanger_analysis.py", line 799, in analyze_sample
    alignment.align_all()
  File "/home/ccadmin/anaconda3/envs/ice_env/lib/python3.8/site-packages/ice/classes/pair_alignment.py", line 94, in align_all
    self.all_aligned_clustal = self.align_list_to_clustal(aln, "control", "edited")
  File "/home/ccadmin/anaconda3/envs/ice_env/lib/python3.8/site-packages/ice/classes/pair_alignment.py", line 80, in align_list_to_clustal
    alignment_txt = aln_objs[0].format("clustal").split('\n', 2)[2]
AttributeError: 'MultipleSeqAlignment' object has no attribute 'format'
```

I'd appreciate your help in troubleshooting this.

**Comment by zhoubin1999** [comment]
change `format` to `__format__`

**Comment by innoxHenan** [comment]
Hi, I've encoutered the same error message. I tried change 'format' to '__format__' for analysis.py, sanger_analysis.py and pair_alignment.py, but it did not work. How did you solve it?

**Comment by thuanguyen** [comment]
I have a same problem. please help.

**Comment by thuanguyen** [comment]
> change `format` to `__format__`

I do not understand what do you mean by change `format` to `__format__`. In which file I need to change it?

**Comment by asyafiqe** [comment]
> > change `format` to `__format__`
> 
> I do not understand what do you mean by change `format` to `__format__`. In which file I need to change it?

pair_alignment.py, line 80
`alignment_txt = aln_objs[0].__format__("clustal").split('\n', 2)[2]`

**Comment by einsidhe** [comment]
Hi folks.
Actually changing 'format' to '__format__' doesn't help.
Have anybody found the solution?

**Comment by sshen8** [comment]
I was able to get around this issue with
`pip install biopython==1.78`
MultipleSeqAlignment.format was deprecated and removed after biopython v1.78 ([docs](https://biopython.org/docs/1.78/api/Bio.Align.html#Bio.Align.MultipleSeqAlignment.format))
